name: datatree-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - netcdf4
  - pytest
  - flake8
  - black
  - codecov
  - pytest-cov
  - h5netcdf
  - zarr
  - pip:
      - "xarray>=2022.06.0, <=2024.07.0"
