name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: datatree
          environment-file: ci/environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install datatree
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        shell: bash -l {0}
        run: |
          python -m pytest --cov=./ --cov-report=xml --verbose
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2.0.2
      #   if: ${{ matrix.python-version }} == 3.8
      #   with:
      #     file: ./coverage.xml
      #     fail_ci_if_error: false

  test-upstream:
    name: ${{ matrix.python-version }}-dev-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: datatree
          environment-file: ci/environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install dev reqs
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps --upgrade \
            git+https://github.com/pydata/xarray \
            git+https://github.com/Unidata/netcdf4-python
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        shell: bash -l {0}
        run: |
          python -m pytest --verbose
